python_library(
  dependencies=[
    'pants-plugins/structured/3rdparty',
    'pants-plugins/structured/subsystems',
    'pants-plugins/structured/targets',
    'pants-plugins/structured/tasks',
  ],
  provides=setup_py(
    name='structured',
    version=commons_version(),
    description='R language pipeline, as a Pants plugin.',
    namespace_packages=['structured'],
    url='https://github.com/cosmicexplorer/structured',
    license='Apache License, Version 2.0',
    zip_safe=True,
    classifiers=[
      'Intended Audience :: Developers',
      'License :: OSI Approved :: Apache Software License',
      'Operating System :: MacOS :: MacOS X',
      'Operating System :: POSIX :: Linux',
      'Programming Language :: Python',
      'Programming Language :: R',
      'Topic :: Software Development :: Build Tools',
    ],
  ),
)
