python_library(
  sources=rglobs('*.py'),
  provides=setup_py(
    name='structured',
    version=commons_version(),
    description='R language pipeline, as a Pants plugin.',
    namespace_packages=['structured'],
    url='https://github.com/cosmicexplorer/structured',
    license='GPL-3.0+',
    zip_safe=True,
    classifiers=[
      'Intended Audience :: Developers',
      'License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)',
      'Operating System :: MacOS :: MacOS X',
      'Operating System :: POSIX :: Linux',
      'Programming Language :: Python',
      'Programming Language :: R',
      'Topic :: Software Development :: Build Tools',
    ],
  ),
)
