python_library(
  sources=rglobs('*.py'),
  provides=setup_py(
    name='r-pants',
    version=commons_version(),
    description='R language pipeline, as a Pants plugin.',
    url='https://github.com/cosmicexplorer/r-pants',
    license='GPL-3.0+',
    zip_safe=True,
    classifiers=[
      'Intended Audience :: Developers',
      'License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)',
      'Programming Language :: Python, R',
      'Programming Language :: R',
    ],
  ),
)
